name: Multiverse-Core
main: com.onarandombox.MultiverseCore.MultiverseCore
authors: ['dumptruckman', 'Rigby', 'fernferret', 'lithium3141', 'main--']
website: 'https://dev.bukkit.org/projects/multiverse-core'
softdepend: ['Vault']
api-version: 1.13
version: maven-version-number
commands:
  mv:
    description: Generic Multiverse Command
    usage: /<command>
  mvtp:
    description: Command to teleport between Worlds
    usage: /<command> [player] <destination>
  mvsetspawn:
    description: Set the spawn area for a particular world
    usage: /<command>
  mvspawn:
    description: Go to spawn of a particular world.
    usage: /<command> [player]
  mvm:
    description: Modify properties for a particular world
    usage: /<command> <set|add|remove|clear> <property> [value] [world]
  mvp:
    description: Generic Multiverse-Portals Command
    usage: /<command>
  mvnp:
    description: Generic Multiverse-NetherPortals Command
    usage: /<command>
  mvinv:
    description: Generic Multiverse-Inventories Command
    usage: /<command>
